-- -----------------------------------
-- Table structure for `alarms`
-- -----------------------------------

DROP TABLE IF EXISTS `alarms`;
CREATE TABLE `alarms` (
  `ZoneNo` int(2) DEFAULT NULL,
  `Start Time 1` int(4) DEFAULT NULL,
  `End Time 1` int(4) DEFAULT NULL,
  `Start Time 2` int(4) DEFAULT NULL,
  `End Time 2` int(4) DEFAULT NULL,
  `Debounce Delay` int(1) DEFAULT NULL,
  `Skip Delay` int(1) DEFAULT NULL,
  `Initiating type` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `Alarmcode` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `Restoralcode` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `InputNo` int(2) DEFAULT NULL,
  `Softzone No. on arming` int(1) DEFAULT NULL,
  `Softzone no. on disarming` int(1) DEFAULT NULL,
  `Siren Delayed` int(1) DEFAULT NULL,
  `Sounding type 1` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `Sounding type 2` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `Siren Type` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `InactiveReporting` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `ArmZone` varchar(9) CHARACTER SET utf8 DEFAULT NULL,
  `Restoral Allowed` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `Contact Type` varchar(15) CHARACTER SET utf8 DEFAULT NULL,
  `CRA zone` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `Descriptor` varchar(16) CHARACTER SET utf8 DEFAULT NULL,
  `User 0` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 1` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `User 2` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `User 3` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `User 4` varchar(3) CHARACTER SET utf8 DEFAULT NULL,
  `User 5` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 6` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 7` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 8` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 9` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 10` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 11` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 12` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 13` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 14` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 15` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 16` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 17` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 18` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `User 19` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `Camera` varchar(30) CHARACTER SET utf8 NOT NULL DEFAULT 'Lobby',
  `SH` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'S',
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=61 DEFAULT CHARSET=latin1;

