-- -----------------------------------
-- Table structure for `gpssites`
-- -----------------------------------

DROP TABLE IF EXISTS `gpssites`;
CREATE TABLE `gpssites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ATMID` varchar(100) CHARACTER SET utf8 NOT NULL,
  `Address` varchar(600) CHARACTER SET utf8 NOT NULL,
  `Location` text CHARACTER SET utf8 NOT NULL,
  `State` varchar(100) CHARACTER SET utf8 NOT NULL,
  `IPAddress` varchar(50) CHARACTER SET utf8 NOT NULL,
  `Rourt ID` varchar(100) CHARACTER SET utf8 NOT NULL,
  `LiveDate` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `UserName` varchar(50) CHARACTER SET utf8 NOT NULL,
  `Password` varchar(50) CHARACTER SET utf8 NOT NULL,
  `Status` varchar(5) CHARACTER SET utf8 NOT NULL,
  `dvrname` varchar(10) CHARACTER SET utf8 NOT NULL,
  `customer` varchar(15) CHARACTER SET utf8 NOT NULL,
  `Bank` varchar(10) CHARACTER SET utf8 NOT NULL,
  `ATMID2` varchar(60) CHARACTER SET utf8 NOT NULL,
  `remark` text CHARACTER SET utf8 NOT NULL,
  `zone` varchar(20) CHARACTER SET utf8 NOT NULL,
  `city` varchar(20) CHARACTER SET utf8 NOT NULL,
  `old_atm` varchar(20) CHARACTER SET utf8 NOT NULL,
  `installationDate` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `project` varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT 'GPS',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=latin1;

INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('1', 'MPZ07241', ' mukhim siddaqi  Near Swaraj Tractor Showroom, Pavanraje Showroom, Osmanabad - 413501', 'Osmanabad', 'Maharashtra', '172.55.22.75', '', '44691', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44690', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('2', 'MPZ07224', 'Ladalesahab haware pawan raje mulistate patel complex opp pathan hospital paranda 413502 distric usmanabad ', 'Osmanabad', 'Maharashtra ', '172.55.23.159', '-', '44725', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44622', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('3', 'MPZ07334', 'PAVANRAJE COMPLEX, GANDHI NAGAR, OSMANABAD – 413501', 'Osmanabad', 'Maharashtra ', '10.185.183.121', '-', '44744', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44723', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('4', 'MPZ07383', 'Balaji Colony, Near HDFC Bank, Solapur Road, Barshi, Dist. Solapur 413401', 'Solapur', 'Maharashtra ', '172.55.22.107', '-', '44727', 'admin', 'css12345', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Solapur', '-', '44690', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('5', 'MPZ07474', 'Village Banshariya Opposite maruti Plant gate no 1 Sector 8 IMT Manesar Gurgaon Haryana 122051', 'Gurgaon', 'Haryana', '10.109.70.70 ', '', '44694', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Gurgaon', '-', '44673', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('6', 'MPZ07503', 'C/O Motilal Yadav, Airport road Veer Kunwar Singh Colony, P.O:-Hinoo, P.S:-Doranda, Dist:-Ranchi, Jharkhand, PIN:-834002', 'Ranchi', 'Jharkhand', '172.55.51.253', '-', '44720', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'East', 'Ranchi', '-', '44682', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('7', 'MPZ07618', 'Utkarsh Solution Jadhav Kirana Store , near bandhan bank , mahatama Gandhi nagar , Osmanabad 413501', 'Osmanabad', 'Maharashtra ', '172.55.22.127', '-', '44691', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44690', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('8', 'MPZ07693', 'Pavanraje Loksamruddhi Multistate Co op Credit Society,Main Road, Osmanabad - 413501', 'Osmanabad', 'Maharashtra ', '172.55.23.183', '-', '44746', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44704', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('9', 'MPZ08688', ' sandesh kumar kantilal doshi survy number 4075/23 milistone near bhosale ice cream kadabe galli pandharpur 413304', 'Pandharpur', 'Maharashtra ', '172.55.51.250', '-', '44692', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Pandharpur', '-', '44588', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('10', 'MPZ07895', 'WARD NO 17, ADARSH COLONY RUDRAPUR - Uttrakhand - 263153', 'Rudrapur', 'Uttrakhand', '10.109.68.206', '-', '44695', 'admin', 'css12345', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Rudrapur', '-', '44685', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('11', 'MPZ08211', 'HP Petrol Pump,Near ESI Hospital, Sector-03,Dist-Gurugram, Haryana - 122051', 'Gurugaram', 'Haryana', '10.109.66.19', '-', '44691', 'admin', 'admin', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Gurugaram', '-', '44690', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('12', 'MPZ08413', 'IMT Chowk,Sec-2,IMT manesar,Distt-Gurugram,Haryana pin code 122052', 'Gurugaram', 'Haryana', '10.109.71.64', '-', '44691', 'admin', 'admin', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Gurugaram', '-', '44690', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('13', 'MPZ08414', 'Near Denso Crafting The Core Company,Sector-3,Imt Manesar, Gurugram, Haryana pin code 122051', 'Gurugaram', 'Haryana', '10.109.71.47', '-', '44691', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Gurugaram', '-', '44691', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('14', 'MPZ08771', 'HARIPUR URBAN, NEAR VITTHAL MANDIR, AT POST HARIPUR,NEAR HARIPUR URBAN NIDHI SANGLI - 416416', 'Sangli', 'Maharashtra ', '172.55.51.242', '-', '44624', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Sangli', '-', '44590', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('15', 'MPZ08772', ' HARIPUR URBAN, NEAR VITTHAL MANDIR, AT POST HARIPUR,NEAR HARIPUR URBAN NIDHI SANGLI - 416416', 'Sangli', 'Maharashtra ', '172.55.51.241', '-', '44624', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Sangli', '-', '44597', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('16', 'MPZ10725', 'Opposite of HDFC branch, Chacha colony,Renukoot,Sonebhadra, Utter Pardesh, 231217', 'Sonbhadra', 'Uttar Pradesh', '172.55.23.198', 'gigatek', '45227', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Sonbhadra', '-', '45051', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('17', 'MPZ08687', 'dvp mertiple state copretive socity limited  opp  DCC bank nvdurg road tuljapur  distric usmanabad 413601 ', 'Osmanabad', 'Maharashtra ', '172.55.23.169', '-', '44690', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44621', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('18', 'MPZ08914', 'anil auto mobile kachehri road mainpuri near RC college pin 205001', 'Manipuri', 'Uttar Pradesh', '172.55.23.84', '', '44653', 'admin', 'css12345', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Manipuri', '-', '44600', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('19', 'MPZ05659', 'Purani Durga mandir kasba tajpur samastipur bihar 848130', 'Samastipur', 'Bihar', '10.109.70.123', '-', '45226', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'East', 'Samastipur', '-', '45252', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('20', 'MPZ08643', 'Near Vyanktesh Colony KDK College Road Nagpur 440009', 'Nagpur', 'Maharashtra ', '10.109.64.170', 'CREDO', '44813', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Nagpur', '-', '45240', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('21', 'MPZ10129', 'Sector 3, Water Supply Road, Near Bundy India Limited , Imt Manesar, Gurugram, Haryana 122051', 'Gurugaram', 'Haryana', ' 10.109.65.188', '-', '44831', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'North', 'Gurugaram', '-', '44809', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('22', 'MPZ07694', 'Mumbai - Kolkata Hwy, Chinchbhuwan, Maharashtra 440023 Near HP petrol pump 14 mile', 'Nagpur', 'Maharashtra ', '10.109.70.136', '-', '44692', 'admin', 'admin', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Nagpur', '-', '44693', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('23', 'MPZ07767', 'Pavanraje Loksamruddhi Multistate Co op Credit Society,Main Road, Osmanabad - 413501', 'Osmanabad', 'Maharashtra ', '172.55.22.73', '-', '44691', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', '-', 'West', 'Osmanabad', '-', '44572', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('24', 'MPZ12498', 'Gate No-2, Sector 59 matro station, Main Road, Mamura, Noida UP 201301', '-', 'Noida, UP', '172.55.23.185', 'gigatek', '45266', 'admin', 'no pasword', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', 'This sites camera material used from dismantle sits( MPZ08559) installer suraj ', 'North', '-', '-', '06-12-2023(GPS WILL EXPIR ON 30 JAN-2024', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('25', 'MPZ12755', 'shaibzada ajit singh nagar,punjab,india,unnamed road sector 61, sahibzada ajit singh nagar, chandigarh, punjab,160062,india', '-', 'PUNJAB', ' 10.109.66.45', 'CREDO', '45259', '-', '-', 'Y', 'Hikvision', 'Hitachi', 'WLA', '-', 'This sites camera material used from dismantle sits (ali)', 'North', '-', '-', '45306', '-');
INSERT INTO `gpssites` (`id`, `ATMID`, `Address`, `Location`, `State`, `IPAddress`, `Rourt ID`, `LiveDate`, `UserName`, `Password`, `Status`, `dvrname`, `customer`, `Bank`, `ATMID2`, `remark`, `zone`, `city`, `old_atm`, `installationDate`, `project`) VALUES ('26', '', '', '', '', '', '', '', '', '', 'Y', 'Hikvision', '', '', '', '', '', '', '', '', '');
