-- -----------------------------------
-- Table structure for `rms_update`
-- -----------------------------------

DROP TABLE IF EXISTS `rms_update`;
CREATE TABLE `rms_update` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `rms_id` int(6) DEFAULT NULL,
  `panel_install` varchar(20) DEFAULT NULL,
  `panel_alert` varchar(30) DEFAULT NULL,
  `panel_serial` varchar(30) DEFAULT NULL,
  `panel_remark` text,
  `relay_install` varchar(20) DEFAULT NULL,
  `relay_alert` varchar(30) DEFAULT NULL,
  `relay_serial` varchar(30) DEFAULT NULL,
  `relay_remark` text,
  `panic_install` varchar(20) DEFAULT NULL,
  `panic_alert` varchar(30) DEFAULT NULL,
  `panic_serial` varchar(30) DEFAULT NULL,
  `panic_remark` text,
  `glass_install` varchar(20) DEFAULT NULL,
  `glass_alert` varchar(30) DEFAULT NULL,
  `glass_serial` varchar(30) DEFAULT NULL,
  `glass_remark` text,
  `backroom_install` varchar(20) DEFAULT NULL,
  `backroom_alert` varchar(30) DEFAULT NULL,
  `backroom_serial` varchar(30) DEFAULT NULL,
  `backroom_remark` text,
  `keypad_install` varchar(20) DEFAULT NULL,
  `keypad_alert` varchar(30) DEFAULT NULL,
  `keypad_serial` varchar(30) DEFAULT NULL,
  `keypad_remark` text,
  `cctv_install` varchar(20) DEFAULT NULL,
  `cctv_alert` varchar(30) DEFAULT NULL,
  `cctv_serial` varchar(30) DEFAULT NULL,
  `cctv_remark` text,
  `spk_install` varchar(20) DEFAULT NULL,
  `spk_alert` varchar(30) DEFAULT NULL,
  `spk_serial` varchar(30) DEFAULT NULL,
  `spk_remark` text,
  `ac_install` varchar(20) DEFAULT NULL,
  `ac_alert` varchar(30) DEFAULT NULL,
  `ac_serial` varchar(30) DEFAULT NULL,
  `ac_remark` text,
  `smoke_install` varchar(20) DEFAULT NULL,
  `smoke_alert` varchar(30) DEFAULT NULL,
  `smoke_serial` varchar(30) DEFAULT NULL,
  `smoke_remark` text,
  `tamper_swith_install` varchar(20) DEFAULT NULL,
  `tamper_swith_alert` varchar(30) DEFAULT NULL,
  `tamper_swith_serial` varchar(30) DEFAULT NULL,
  `tamper_swith_remark` text,
  `upsAlert_install` varchar(20) DEFAULT NULL,
  `upsAlert_alert` varchar(30) DEFAULT NULL,
  `upsAlert_serial` varchar(30) DEFAULT NULL,
  `upsAlert_remark` text,
  `acmain_install` varchar(20) DEFAULT NULL,
  `acmain_alert` varchar(30) DEFAULT NULL,
  `acmain_serial` varchar(30) DEFAULT NULL,
  `acmain_remark` text,
  `siren_install` varchar(20) DEFAULT NULL,
  `siren_alert` varchar(30) DEFAULT NULL,
  `siren_serial` varchar(30) DEFAULT NULL,
  `siren_remark` text,
  `lobbypir_install` varchar(20) DEFAULT NULL,
  `lobbypir_alert` varchar(30) DEFAULT NULL,
  `lobbypir_serial` varchar(30) DEFAULT NULL,
  `lobbypir_remark` text,
  `atmdoor_install` varchar(20) DEFAULT NULL,
  `atmdoor_alert` varchar(30) DEFAULT NULL,
  `atmdoor_serial` varchar(30) DEFAULT NULL,
  `atmdoor_remark` text,
  `lobbytemp_install` varchar(20) DEFAULT NULL,
  `lobbytemp_alert` varchar(30) DEFAULT NULL,
  `lobbytemp_serial` varchar(30) DEFAULT NULL,
  `lobbytemp_remark` text,
  `router_install` varchar(20) DEFAULT NULL,
  `router_alert` varchar(30) DEFAULT NULL,
  `router_serial` varchar(30) DEFAULT NULL,
  `router_remark` text,
  `sim_install` varchar(20) DEFAULT NULL,
  `sim_alert` varchar(30) DEFAULT NULL,
  `sim_serial` varchar(30) DEFAULT NULL,
  `sim_remark` text,
  `battery_install` varchar(20) DEFAULT NULL,
  `battery_alert` varchar(30) DEFAULT NULL,
  `battery_serial` varchar(30) DEFAULT NULL,
  `battery_remark` text,
  `atmChest_install` varchar(20) DEFAULT NULL,
  `atmChest_alert` varchar(30) DEFAULT NULL,
  `atmChest_serial` varchar(30) DEFAULT NULL,
  `atmChest_remark` text,
  `atmHood_install` varchar(20) DEFAULT NULL,
  `atmHood_alert` varchar(30) DEFAULT NULL,
  `atmHood_serial` varchar(30) DEFAULT NULL,
  `atmHood_remark` text,
  `atmRemoval_install` varchar(20) DEFAULT NULL,
  `atmRemoval_alert` varchar(30) DEFAULT NULL,
  `atmRemoval_serial` varchar(30) DEFAULT NULL,
  `atmRemoval_remark` text,
  `atmVibration_install` varchar(20) DEFAULT NULL,
  `atmVibration_alert` varchar(30) DEFAULT NULL,
  `atmVibration_serial` varchar(30) DEFAULT NULL,
  `atmVibration_remark` text,
  `atmThermal_install` varchar(20) DEFAULT NULL,
  `atmThermal_alert` varchar(30) DEFAULT NULL,
  `atmThermal_serial` varchar(30) DEFAULT NULL,
  `atmThermal_remark` text,
  `check_install` varchar(20) DEFAULT NULL,
  `cdb_alert` varchar(30) DEFAULT NULL,
  `cdb_serial` varchar(30) DEFAULT NULL,
  `cdb_remark` text,
  `lobbyCamera_install` varchar(20) DEFAULT NULL,
  `lobbyCamera_alert` varchar(30) DEFAULT NULL,
  `lobbyCamera_serial` varchar(30) DEFAULT NULL,
  `lobbyCamera_remark` text,
  `backRoomcam_install` varchar(20) DEFAULT NULL,
  `backRoomcam_alert` varchar(30) DEFAULT NULL,
  `backRoomcam_serial` varchar(30) DEFAULT NULL,
  `backRoomcam_remark` text,
  `outdoor_install` varchar(20) DEFAULT NULL,
  `outdoor_alert` varchar(30) DEFAULT NULL,
  `outdoor_serial` varchar(30) DEFAULT NULL,
  `outdoor_remark` text,
  `dvr_install` varchar(20) DEFAULT NULL,
  `dvr_alert` varchar(30) DEFAULT NULL,
  `dvr_serial` varchar(30) DEFAULT NULL,
  `dvr_remark` text,
  `hdd_install` varchar(20) DEFAULT NULL,
  `hdd_alert` varchar(30) DEFAULT NULL,
  `hdd_serial` varchar(30) DEFAULT NULL,
  `hdd_remark` text,
  `panel_img` varchar(100) DEFAULT NULL,
  `relay_img` varchar(100) DEFAULT NULL,
  `panic_img` varchar(100) DEFAULT NULL,
  `glass_img` varchar(100) DEFAULT NULL,
  `backroomeml_img` varchar(100) DEFAULT NULL,
  `keypad_img` varchar(100) DEFAULT NULL,
  `cctv_img` varchar(100) DEFAULT NULL,
  `spk_img` varchar(100) DEFAULT NULL,
  `ac_img` varchar(100) DEFAULT NULL,
  `smoke_img` varchar(100) DEFAULT NULL,
  `tamper_swith_img` varchar(100) DEFAULT NULL,
  `upsAlert_img` varchar(100) DEFAULT NULL,
  `acmain_img` varchar(100) DEFAULT NULL,
  `siren_img` varchar(100) DEFAULT NULL,
  `lobbypir_img` varchar(100) DEFAULT NULL,
  `atmdoor_img` varchar(100) DEFAULT NULL,
  `lobbytemp_img` varchar(100) DEFAULT NULL,
  `router_img` varchar(100) DEFAULT NULL,
  `sim_img` varchar(100) DEFAULT NULL,
  `battery_img` varchar(100) DEFAULT NULL,
  `atmChest_img` varchar(100) DEFAULT NULL,
  `atmHood_img` varchar(100) DEFAULT NULL,
  `atmRemoval_img` varchar(100) DEFAULT NULL,
  `atmVibration_img` varchar(100) DEFAULT NULL,
  `atmThermal_img` varchar(100) DEFAULT NULL,
  `cdb_img` varchar(100) DEFAULT NULL,
  `lobbyCamera_img` varchar(100) DEFAULT NULL,
  `backroomcam_img` varchar(100) DEFAULT NULL,
  `outdoor_img` varchar(100) DEFAULT NULL,
  `dvr_img` varchar(100) DEFAULT NULL,
  `hdd_img` varchar(100) DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

