-- -----------------------------------
-- Table structure for `securico`
-- -----------------------------------

DROP TABLE IF EXISTS `securico`;
CREATE TABLE `securico` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `zone` varchar(22) CHARACTER SET utf8 DEFAULT NULL,
  `sensorname` varchar(59) CHARACTER SET utf8 DEFAULT NULL,
  `code` varchar(14) CHARACTER SET utf8 DEFAULT NULL,
  `COL 5` varchar(17) CHARACTER SET utf8 DEFAULT NULL,
  `COL 6` varchar(18) CHARACTER SET utf8 DEFAULT NULL,
  `COL 7` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `COL 8` varchar(14) CHARACTER SET utf8 DEFAULT NULL,
  `COL 9` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `COL 10` varchar(22) CHARACTER SET utf8 DEFAULT NULL,
  `priority` char(1) CHARACTER SET utf8 NOT NULL,
  `camera` varchar(20) CHARACTER SET utf8 NOT NULL,
  `scode` char(2) CHARACTER SET utf8 NOT NULL DEFAULT 'BA',
  `comfort_code` varchar(15) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=44 DEFAULT CHARSET=latin1;

INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('1', '001', 'Lobby PIR Motion sensor', 'NBA001', 'NBR001', 'NDA001', 'NA', 'NA', 'NAK001', 'NAS001', 'Y', 'Lobby Cam', 'BA', 'MA');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('2', '002', 'Glass Break Sensor', 'NBA002', 'NBR002', 'NDA002', 'NA', 'NA', 'NAK002', 'NAS002', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('3', '003', 'Panic Alert', 'NBA003', 'NBR003', 'NDA003', 'NA', 'NA', 'NAK003', 'NAS003', 'R', 'Lobby Cam', 'BA', 'PA');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('4', '004', 'Main Door sensor', 'NBA004', 'NBR004', 'NDA004', 'NA', 'NA', 'NAK004', 'NAS004', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('5', '005', 'ATM Removal', 'NBA005', 'NBR005', 'NDA005', 'NA', 'NA', 'NAK005', 'NAS005', 'R', 'Lobby Cam', 'BA', 'AR');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('6', '006', 'ATM Vibration', 'NBA006', 'NBR006', 'NDA006', 'NA', 'NA', 'NAK006', 'NAS006', 'R', 'Lobby Cam', 'BA', 'AV');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('7', '007', 'ATM Thermal Sensor', 'NBA007', 'NBR007', 'NDA007', 'NA', 'NA', 'NAK007', 'NAS007', 'R', 'Lobby Cam', 'BA', 'AT');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('8', '008', 'Chest Door Open Sensor', 'NBA008', 'NBR008', 'NDA008', 'NA', 'NA', 'NAK008', 'NAS008', 'R', 'Lobby Cam', 'BA', 'CD');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('9', '009', 'ATM Removal', 'NBA009', 'NBR009', 'NDA009', 'NA', 'NA', 'NAK009', 'NAS009', 'R', 'Lobby Cam', 'BA', 'AR');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('10', '010', 'ATM Vibration', 'NBA010', 'NBR010', 'NDA010', 'NA', 'NA', 'NAK010', 'NAS010', 'R', 'Lobby Cam', 'BA', 'AV');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('11', '011', 'ATM Thermal Sensor', 'NBA011', 'NBR011', 'NDA011', 'NA', 'NA', 'NAK011', 'NAS011', 'R', 'Lobby Cam', 'BA', 'AH');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('12', '012', 'Chest Door Open Sensor', 'NBA012', 'NBR012', 'NDA012', 'NA', 'NA', 'NAK012', 'NAS012', 'R', 'Lobby Cam', 'BA', 'CD');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('13', '013', 'Hood Door Open Sensor', 'NBA013', 'NBR013', 'NDA013', 'NA', 'NA', 'NAK013', 'NAS013', 'R', 'Lobby Cam', 'BA', 'HD');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('14', '014', 'ATM Removal', 'NBA014', 'NBR014', 'NDA014', 'NA', 'NA', 'NAK014', 'NAS014', 'R', 'Lobby Cam', 'BA', 'AR');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('15', '015', 'ATM Vibration', 'NBA015', 'NBR015', 'NDA015', 'NA', 'NA', 'NAK015', 'NAS015', 'R', 'Lobby Cam', 'BA', 'AV');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('16', '016', 'ATM Thermal Sensor', 'NBA016', 'NBR016', 'NDA016', 'NA', 'NA', 'NAK016', 'NAS016', 'R', 'Lobby Cam', 'BA', 'AH');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('17', '017', 'Chest Door Open Sensor', 'NBA017', 'NBR017', 'NDA017', 'NA', 'NA', 'NAK017', 'NAS017', 'R', 'Lobby Cam', 'BA', 'CD');
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('18', '018', 'AC Removal', 'NBA018', 'NBR018', 'NDA018', 'NA', 'NA', 'NAK018', 'NAS018', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('19', '019', 'Cheque Drop Box Removal', 'NBA019', 'NBR019', 'NDA019', 'NA', 'NA', 'NAK019', 'NAS019', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('20', '020', 'Cheque Drop Box Removal', 'NBA020', 'NBR020', 'NDA020', 'NA', 'NA', 'NAK020', 'NAS020', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('21', '021', 'Back room Door sensor', 'NBA021', 'NBR021', 'NDA021', 'NA', 'NA', 'NAK021', 'NAS021', 'R', 'Backroom', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('22', '022', 'Lobby Temprature Sensor', 'NBA022', 'NBR022', 'NDA022', 'NA', 'NA', 'NAK022', 'NAS022', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('23', '023', 'Panel Tamper Switch', 'NBA023', 'NBR023', 'NDA023', 'NA', 'NA', 'NAK023', 'NAS023', 'Y', 'Backroom', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('24', '024', 'Lobby Temprature Sensor', 'NBA024', 'NBR024', 'NDA024', 'NA', 'NA', 'NAK024', 'NAS024', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('25', '025', 'Camera Removal', 'NBA025', 'NBR025', 'NDA025', 'NA', 'NA', 'NAK025', 'NAS025', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('26', '026', 'Speaker / MIC Removal', 'NBA026', 'NBR026', 'NDA026', 'NA', 'NA', 'NAK026', 'NAS026', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('27', '027', 'AC Mains (DI)', 'NBA027', 'NBR027', 'NDA027', 'NA', 'NA', 'NAK027', 'NAS027', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('28', '028', 'UPS O/P (DI)', 'NBA028', 'NBR028', 'NDA028', 'NA', 'NA', 'NAK028', 'NAS028', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('29', '029', '', 'NBA029', 'NBR029', 'NDA029', 'NA', 'NA', 'NAK029', 'NAS029', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('30', '030', '', 'NBA030', 'NBR030', 'NDA030', 'NA', 'NA', 'NAK030', 'NAS030', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('31', '031', '', 'NBA031', 'NBR031', 'NDA031', 'NA', 'NA', 'NAK031', 'NAS031', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('32', 'Sounder Silence Switch', '', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('33', '033', '', 'NBA033', 'NBR033', 'NDA033', 'NA', 'NA', 'NAK033', 'NAS033', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('34', '034', '', 'NBA034', 'NBR034', 'NDA034', 'NA', 'NA', 'NAK034', 'NAS034', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('35', '035', '', 'NBA035', 'NBR035', 'NDA035', 'NA', 'NA', 'NAK035', 'NAS035', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('36', '036', '', 'NBA036', 'NBR036', 'NDA036', 'NA', 'NBS036', 'NAK036', 'NAS036', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('39', 'Temperature Sensor', '', 'NBA039', 'NBR039', 'NDA039', 'NBD039', 'NA', 'NAK039', 'NAS039', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('40', 'Light Sensor', '', 'NBA040', 'NBR040', 'NDA040', 'NBD040', 'NA', 'NAK040', 'NAS040', 'B', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('41', '041', 'Smoke Detector', 'NBA041', 'NBR041', 'NDA041', 'NBD041', 'NA', 'NAK041', 'NAS041', 'R', 'Lobby Cam', 'BA', NULL);
INSERT INTO `securico` (`id`, `zone`, `sensorname`, `code`, `COL 5`, `COL 6`, `COL 7`, `COL 8`, `COL 9`, `COL 10`, `priority`, `camera`, `scode`, `comfort_code`) VALUES ('42', '100', 'Sounder', 'NRC100', 'NRO100', NULL, NULL, NULL, NULL, NULL, 'B', 'Lobby Cam', 'BA', NULL);
