-- -----------------------------------
-- Table structure for `site_testing_log`
-- -----------------------------------

DROP TABLE IF EXISTS `site_testing_log`;
CREATE TABLE `site_testing_log` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `backroom` varchar(50) CHARACTER SET utf8 NOT NULL,
  `rebackroom` text CHARACTER SET utf8 NOT NULL,
  `panic` varchar(50) CHARACTER SET utf8 NOT NULL,
  `repanic` text CHARACTER SET utf8 NOT NULL,
  `twoway` varchar(50) CHARACTER SET utf8 NOT NULL,
  `retwoway` text CHARACTER SET utf8 NOT NULL,
  `glass` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reglass` text CHARACTER SET utf8 NOT NULL,
  `Camara` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reCamara` text CHARACTER SET utf8 NOT NULL,
  `bCamara` varchar(50) CHARACTER SET utf8 NOT NULL,
  `rebCamara` text CHARACTER SET utf8 NOT NULL,
  `oCamara` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reobCamara` text CHARACTER SET utf8 NOT NULL,
  `HDD` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reHDD` text CHARACTER SET utf8 NOT NULL,
  `entrydt` datetime NOT NULL,
  `eng_name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `testby` varchar(50) CHARACTER SET utf8 NOT NULL,
  `dvrip` varchar(50) CHARACTER SET utf8 NOT NULL,
  `panel` varchar(50) CHARACTER SET utf8 NOT NULL,
  `repanel` text CHARACTER SET utf8 NOT NULL,
  `paneltemper` varchar(50) CHARACTER SET utf8 NOT NULL,
  `repaneltemper` text CHARACTER SET utf8 NOT NULL,
  `dvrstatus` varchar(50) CHARACTER SET utf8 NOT NULL,
  `redvrstatus` text CHARACTER SET utf8 NOT NULL,
  `dvrvol` varchar(50) CHARACTER SET utf8 NOT NULL,
  `redvrvol` text CHARACTER SET utf8 NOT NULL,
  `eml` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reeml` text CHARACTER SET utf8 NOT NULL,
  `upscable` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reupscable` text CHARACTER SET utf8 NOT NULL,
  `keypad` varchar(50) CHARACTER SET utf8 NOT NULL,
  `rekeypad` text CHARACTER SET utf8 NOT NULL,
  `Antenna` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reAntenna` text CHARACTER SET utf8 NOT NULL,
  `pirsensor` varchar(50) CHARACTER SET utf8 NOT NULL,
  `repirsensor` text CHARACTER SET utf8 NOT NULL,
  `Smoke` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reSmoke` text CHARACTER SET utf8 NOT NULL,
  `Shutter` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reShutter` text CHARACTER SET utf8 NOT NULL,
  `Hooter` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reHooter` text CHARACTER SET utf8 NOT NULL,
  `AC1` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reAC1` text CHARACTER SET utf8 NOT NULL,
  `AC2` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reAC2` text CHARACTER SET utf8 NOT NULL,
  `enableloby` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reenableloby` text CHARACTER SET utf8 NOT NULL,
  `enableback` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reenableback` text CHARACTER SET utf8 NOT NULL,
  `enableOut` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reenableOut` text CHARACTER SET utf8 NOT NULL,
  `dvrtime` varchar(50) CHARACTER SET utf8 NOT NULL,
  `redvrtime` text CHARACTER SET utf8 NOT NULL,
  `recording_scheduling` varchar(50) CHARACTER SET utf8 NOT NULL,
  `rerecording_scheduling` text CHARACTER SET utf8 NOT NULL,
  `Light` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reLight` text CHARACTER SET utf8 NOT NULL,
  `CRAsensor1` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reCRAsensor1` text CHARACTER SET utf8 NOT NULL,
  `CRAsensor2` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reCRAsensor2` text CHARACTER SET utf8 NOT NULL,
  `CRAsensor3` varchar(50) CHARACTER SET utf8 NOT NULL,
  `reCRAsensor3` text CHARACTER SET utf8 NOT NULL,
  `hddfoot` varchar(50) CHARACTER SET utf8 NOT NULL,
  `fromdt` varchar(250) CHARACTER SET utf8 DEFAULT NULL,
  `todate` varchar(250) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=140 DEFAULT CHARSET=latin1;

